### ISSUE TITLE
ocean_dataset/elliptic_hyperbolic_lcs.m boundary velocity

### ISSUE THREAD

**Issue by 1520588207** [jeixav/LCS-Tool#10]
there are set the velocity to zero at boundaries. and,why? boundary condition is  necessary? i think, it is not conform to  the real world. thank you!

<img width="255" alt="lcs" src="https://cloud.githubusercontent.com/assets/11959482/13671496/3069029e-e70b-11e5-947e-13bdde19df44.PNG">

https://github.com/jeixav/LCS-Tool/blob/master/demo/ocean_dataset/elliptic_hyperbolic_lcs.m#L11-L14

**Comment by tuxication** [comment]
I would guess this is to stop trajectories at the boundary. Of course it's does not exactly represent the real world but since the velocity and the calculation are done on a finite domain, you have to impose boundary condition. This will not affect the calculation of the main LCSs inside the domain. Of course, you still have to be careful with LCSs on the limit of the domain since trajectories/strainlines are most likely stop and not integrated as long as the ones in the middle of the domain.

**Comment by jeixav** [comment]
@tuxication Your explanation sounds right.
@1520588207 Have you tried deleting those lines to see the result?
@fhuhn Can you provide insight?

**Comment by 1520588207** [comment]
@jeixav  Lines have been commented out,but it can't have a result.Program is running,but no error.

**Comment by jeixav** [comment]
Please try https://github.com/jeixav/LCS-Tool/blob/master/demo/ocean_dataset/elliptic_hyperbolic_lcs_details.m. Does it show output?

**Comment by 1520588207** [comment]
@jeixav thank you,i have reproduced https://gist.github.com/jeixav/595081cba7e090fbed10.it has the result like your result.further,i find i had change some parameters before i delete the boundary condition, so i can't get the figures.after i change it back,i get 
![Uploading alcs2.jpg…]()
![Uploading rLCS2.jpg…]()

**Comment by 1520588207** [comment]
@jeixav thank you,i have reproduced https://gist.github.com/jeixav/595081cba7e090fbed10.it has the result like your result.further,i find i had change some parameters before i delete the boundary condition, so i can't get the figures.after i change it back,i get 
![Uploading alcs2.jpg…]()
![Uploading rLCS2.jpg…]()

**Comment by 1520588207** [comment]
@jeixav thank you,i have reproduced https://gist.github.com/jeixav/595081cba7e090fbed10.it has the result like your result.further,i find i had change some parameters before i delete the boundary condition, so i can't get the figures.after i change it back ,i get 
![alcs2](https://cloud.githubusercontent.com/assets/11959482/13726846/1a834b00-e914-11e5-8543-21afaead4413.jpg)
![rlcs2](https://cloud.githubusercontent.com/assets/11959482/13726850/21db460a-e914-11e5-8e91-eed33d24bf29.jpg)

**Comment by jeixav** [comment]
Looks good! Can you send a [pull request](https://help.github.com/articles/creating-a-pull-request/) with your modifications?

This should allow removing the zero boundary velocity and thereby simplify the example.

**Comment by 1520588207** [comment]
@jeixav i just deleted the boundry condition.

**Comment by jeixav** [comment]
Closed with https://github.com/jeixav/LCS-Tool/pull/11

**Comment by prafulla145** [comment]
Is it possible to use LCS tool code with some modifications so that it can be used to detect OECSs (Serra nd Haller 2016).
