### ISSUE TITLE
High Memory Requirements

### ISSUE THREAD

**Issue by jimme07** [jeixav/LCS-Tool#14]
Is there any minimum system requirement to run the LCS-TOOL. Matlab2013a hangs while running in my 8 Gb machine. The tool works well in a  PC with Xeon 2 X 4 core, 48 Gb RAM. However, it takes up all the RAM (while running on all the cores). 

Can you tell whether the tool needs such high requirements?

**Comment by jeixav** [comment]
Test whether reducing the flow resolution decreases the amount of RAM required. I think RAM amount required is most strongly proportional to flow resolution.

**Comment by jimme07** [comment]
Do you mean the flow resolution to be the resolution of the input
time-series flow data or the resolution of the initial grid for FTLE
calculation?

Jimreeves M
Phd student
Mech - IISc Bangalore
----------------------------------------------------------
http://spinandswirl.wordpress.com/

**Comment by jeixav** [comment]
I mean the grid resolution for FTLE calculations, for example the parameter [resolutionX](https://github.com/jeixav/LCS-Tool/blob/b471a80fe7e2d0d7be915222be9ab01e52d1a7a3/demo/ocean_dataset/elliptic_hyperbolic_lcs.m#L4) in [demo/ocean_dataset/elliptic_hyperbolic_lcs.m](https://github.com/jeixav/LCS-Tool/blob/b471a80fe7e2d0d7be915222be9ab01e52d1a7a3/demo/ocean_dataset/elliptic_hyperbolic_lcs.m).
