### ISSUE TITLE
Dataset from irregular grid

### ISSUE THREAD

**Issue by jimme07** [jeixav/LCS-Tool#3]
I have datasets that are from a irregular grid. Should I interpolate it on to a regular grid of some resolution (say xres* yres) and feed it to LCS tool or I can feed it directly as a irregular data.

**Comment by jeixav** [comment]
LCS Tool requires data on a regular grid. The theory upon which LCS Tool is based can handle irregular grids. If you provide a representative sample from the irregular dataset you have, it may be easier to determine if LCS Tool can process it.
