### ISSUE TITLE
Removing orientation discontinuity for elliptic LCS

### ISSUE THREAD

**Issue by jimme07** [jeixav/LCS-Tool#4]
I want to know how to remove orientational discontinuity for the lambda-line integration, especially at the Initial point (Fig2 in your paper). I want to know which specific functions to use to find the 4 neighbouring vectors for a given points location. 

![image](https://cloud.githubusercontent.com/assets/7112509/8018491/2ebf2838-0c3c-11e5-9cb3-6ba0858b9b2b.png)

**Comment by jeixav** [comment]
The function [integrate_line](https://github.com/jeixav/LCS-Tool/blob/master/integrate_line.m) and its local function [is_element_with_orient_discont](https://github.com/jeixav/LCS-Tool/blob/master/integrate_line.m#L234) handle orientation discontinuity. If you provide sample code, it may be possible to give a more specific answer.
