### ISSUE TITLE
Automated parameter selection

### ISSUE THREAD

**Issue by rshami03** [jeixav/LCS-Tool#6]
In terms of domain, is there a way to automatically detect and assign this for large data sets? i.e. an optimising parameter loop?

**Comment by rshami03** [comment]
*in terms of domain, etc

**Comment by jeixav** [comment]
LCS Tool does not include any code to assist optimized detection in large domains. The results in this publication may be relevant: http://arxiv.org/abs/1404.3109.

**Comment by rshami03** [comment]
I'll look into that. Thank you.
