### ISSUE TITLE
excessive memory use

### ISSUE THREAD

**Issue by jimme07** [jeixav/LCS-Tool#7]
I am running data-sets in LCS Tool on an Intel Xeon (8core) machine with 48 GB ram. (with MATLAB 2013b). The code uses nearly 43 GB ram for a DLE grid of resolution (900x900). 

For cases with slightly higher resolution (e.g. 1100x1100), the memory usage reaches 48 GB and MATLAB crashes. 

Is there a way to prevent this?

**Comment by jeixav** [comment]
Can you examine what LCS Tool function causes excessive memory use?

**Comment by jimme07** [comment]
After the run, I deleted the variable 'lDerivative' and the memory used dropped from 43 Gb to 2 Gb.

**Comment by jeixav** [comment]
Please check if the problem also occurs with this copy of LCS Tool: https://github.com/LCSETH/LCStool. If yes, please open a support request with that project.
