### ISSUE TITLE
algorithm for shrinklines and strechlines

### ISSUE THREAD

**Issue by jimme07** [jeixav/LCS-Tool#8]
Are the seed points chosen as a subset of points which satisfy some condition (like in [DOI:10.1063/1.3690153](http://dx.doi.org/10.1063/1.3690153))?

![grid](https://cloud.githubusercontent.com/assets/7112509/9434580/0349e728-4a5e-11e5-84e6-24818d518397.png)

Apart from the removing orientation discontinuity part which is done locally now, is the remaining part of the algorithm similar to the one given in the DOI referenced above?

**Comment by jeixav** [comment]
[DOI:10.1063/1.3690153](http://dx.doi.org/10.1063/1.3690153) pre-dates LCS Tool and is not a good reference for the algorithms in LCS Tool. For information on LCS Tool's algorithm's, read this document: https://github.com/jeixav/LCS-Tool-Article/.
