### ISSUE TITLE
missing radtodeg.m

### ISSUE THREAD

**Issue by rsignell-usgs** [jeixav/LCS-Tool#9]
Tests fail because 'degtorad' and 'radtodeg' are not found (because mapping toolkit is not installed, I guess?)

Maybe supply these?  
Are they just this?
```
%degtorad.m
function rad = degtorad(deg)
rad = (pi/180.)*deg;
```
```
%radtodeg.m
function deg = radtodeg(rad)
deg = (180./pi)*rad;
```

**Comment by jeixav** [comment]
I think these are core MATLAB functions: http://www.mathworks.com/help/matlab/ref/deg2rad.html.

**Comment by rsignell-usgs** [comment]
@jeixav , awesome!
So maybe the code could call these core functions (`deg2rad` and `rad2deg` instead of  `degtorad` and `radtodeg`)

**Comment by jeixav** [comment]
Sorry, I failed to notice the difference in the names ('2' vs. 'to'). Commit fc0c3c199dae7a2e916b80870259b07c0f03b23c should fix this. Let me know if it does not.
